import Features from "@/components/sections/Features";
import Footer from "@/components/sections/Footer";
import Header from "@/components/sections/Header";
import Hero from "@/components/sections/Hero";
import Testimonials from "@/components/sections/Testimonials";
import Trainer from "@/components/sections/Trainer";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import Aos from "aos";

export default function Home() {
  React.useEffect(() => {
    Aos.init();
  }, []);
  return (
    <>
      <Head>
        <title>FitBody</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/dumble.png" />
      </Head>
      <main>
        <Header />
        <Hero />
        <Features />
        <Trainer />
        <Testimonials />
        <Footer />
      </main>
    </>
  );
}
