import Header from "@/components/sections/Header";
import Hero from "@/components/sections/Hero";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>FitBody</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/dumble.png" />
      </Head>
      <main>
        <Header />
        <Hero />
      </main>
    </>
  );
}
